### ISSUE TITLE
Get-NspTlsReport.ps1 parameter NumberOfHoursToReport throws error message

### ISSUE THREAD

**Issue by marcusb1** [noSpamProxy/Reports#4]
PS D:\script\NSP\NaW-Scripts\Get-NspTlsReport> .\Get-NspTlsReport.ps1 -NumberOfHoursToReport 4
Getting data for E-Mails from External
Get-NspMessageTrack : Cannot bind parameter 'From'. Cannot convert value "10/23/2019 09:52:41" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At D:\script\NSP\NaW-Scripts\Get-NspTlsReport\Get-NspTlsReport.ps1:198 char:41
+             $messageTracks = Get-NSPMessageTrack @cleanedParams -WithOperations -WithDeli ...
+                                                  ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-NspMessageTrack], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Netatwork.NoSpamProxy.PowerShell.Commands.GetNspMessageTrackCommand
 
Getting data for E-Mails from local
Get-NspMessageTrack : Cannot bind parameter 'From'. Cannot convert value "10/23/2019 09:52:41" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At D:\script\NSP\NaW-Scripts\Get-NspTlsReport\Get-NspTlsReport.ps1:198 char:41
+             $messageTracks = Get-NSPMessageTrack @cleanedParams -WithOperations -WithDeli ...
+                                                  ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-NspMessageTrack], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Netatwork.NoSpamProxy.PowerShell.Commands.GetNspMessageTrackCommand
 
Generating Report
Skript durchgelaufen

**Comment by janjaeschke** [comment]
Hello marcsub1,

please try to use ISO 8601 date format: "YYYY-MM-DD hh:mm:ss" .
I will add a validation pattern soon so that the script will not run if another format is used.
It depends on the installed Windows server Eng/Ger if the other formats works directly.

**Comment by janjaeschke** [comment]
A new version of the script is now available.
This version includes a validation pattern so that only time formats like "YYYY-MM-dd hh:mm:ss" are allowed.
The seconds are not necessary.
