### ISSUE TITLE
NoMail does not save to current execution location

### ISSUE THREAD

**Issue by MadnezzzShin** [noSpamProxy/Reports#5]
Hello,

thanks for providing the script first of all.
Get-NspTlsReport states that it saves the report to the current execution location where the switch -NoMail is used.
This doesn't seem to be right, as the variable for the reportFile is "$ENV:TEMP\" + "$ReportFileName" + ".html"

Just tested it this morning and the reportFile is found inside my temp folder

**Comment by janjaeschke** [comment]
Hello MadnezzzShin,

thank you for reporting the issue.
I fixed it already and my tests where successful now.

Kind regards,
Jan
