### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by UmairRaza** [noSpamProxy/Reports#6]
Hello ! I have a no spam proxy on machine and i used the file "Block reports send to Users". I am new to Powershell. By my understanding i run the file in Powershell with some changes. I am not getting results. Can anyone tell me what changes has to be made in the file ?
This is the basic error i am getting "the name  "Get-NSPMessageTrack" was not recognised as the name of a cmdlet, a function of a script file or an executable programme."

Thank You

**Comment by UmairRaza** [comment]
![nsperror](https://user-images.githubusercontent.com/16474123/117432822-11155f80-af2b-11eb-9673-4151ca37ed58.PNG)

**Comment by janjaeschke** [comment]
Hello UmairRaza,

are you running the script from the installed intranet role?
If so please try to run: "Import-Module NoSpamProxy" and then "Get-NspMessageTrack".

The NoSpamProxy CmdLets are required to use this script and those CmdLets are only available at the intranet role itself.

A dependency check is definitely missing here.

Regards,
Jan

**Comment by janjaeschke** [comment]
@UmairRaza did my hint helped you to solve the issue?
